/**
 * Netlify build script — runs before deploy.
 * Generates config.js from environment variables so no secrets
 * are ever committed to the GitHub repository.
 *
 * Required Netlify environment variables:
 *   SUPABASE_URL       — your project URL
 *   SUPABASE_ANON_KEY  — your anon / public key
 */
const fs = require('fs');

const url = process.env.SUPABASE_URL      || '';
const key = process.env.SUPABASE_ANON_KEY || '';

if (!url || !key) {
  console.error('❌  Missing SUPABASE_URL or SUPABASE_ANON_KEY environment variables.');
  console.error('    Set them in Netlify → Project configuration → Environment variables.');
  process.exit(1);
}

fs.writeFileSync('config.js', `/* Auto-generated by build.js — do not edit */
window.SENA_CONFIG = {
  supabaseUrl: '${url}',
  supabaseKey: '${key}',
};
`);

console.log('✅  config.js generated from environment variables.');
